          ffmpeg \
            -hide_banner \
            -re \
            -user_agent "$USER_AGENT" \
            -headers "Referer: $REFERER"$'\r\n'"Origin: https://www.maziika.shop"$'\r\n' \
            -rw_timeout 15000000 \
            -live_start_index -2 \
            -fflags +genpts+discardcorrupt \
            -reconnect 1 -reconnect_delay_max 5 \
            -allowed_extensions ALL \
            -protocol_whitelist file,http,https,tcp,tls,crypto,data \
            -thread_queue_size 10240 \
            -i "$FINAL_URL" \
            -i logo.png \
            -filter_complex "[0:v]fps=30[vid];[1:v]format=rgba,colorchannelmixer=aa=0.85[logo];[logo][vid]scale2ref=w=oh*mdar:h=ih*0.12[scaled_logo][main];[main][scaled_logo]overlay=W-w-(W*0.05):H*0.05,format=yuv420p[outv]" \
            -map "[outv]" \
            -map 0:a:0 \
            -c:v libx264 \
            -preset ultrafast \
            -tune zerolatency \
            -b:v 3000k \
            -maxrate 3500k \
            -bufsize 6000k \
            -g 60 \
            -c:a aac -b:a 128k \
            -f fifo \
            -fifo_format flv \
            -drop_pkts_on_overflow 1 \
            -attempt_recovery 1 \
            -recovery_wait_time 2 \
            -queue_size 200000 \
            "$CLEAN_CH2_RTMP"
