name: Live Stream AP2 (Direct Push Copy)

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install streamlink

      - name: Start Direct Copy Engine
        run: |
          STREAM_URL="https://stream.supertv.gg:3001/supertv/sport/stv1/ch1/ch1_1080.m3u8"
          RTMP_URL="rtmp://vsu.okcdn.ru/input/14574023089903_15258718964463_f7662l35iu"

          while true; do
            echo "🚀 Direct Pushing: Copying source stream to destination..."
            
            # --hls-live-edge 2: البقاء في مقدمة البث الحي (تأخير ثانيتين فقط)
            # --hls-segment-threads 3: سحب اللقطات بـ 3 مسارات لضمان السرعة القصوى
            
            streamlink --stdout \
              --hls-live-restart \
              --hls-live-edge 2 \
              --hls-segment-threads 3 \
              --http-no-ssl-verify \
              --http-header "User-Agent=Mozilla/5.0" \
              --http-header "Referer=https://supertv.gg/" \
              "hls://$STREAM_URL" best | \
              ffmpeg -thread_queue_size 16384 -i pipe:0 \
              -fflags +genpts+igndts+nobuffer \
              -c copy \
              -flvflags no_sequence_end \
              -f flv "$RTMP_URL"

            echo "⚠️ Stream gap detected. Re-pushing in 3 seconds..."
            sleep 3
          done
