name: APiX TV Professional Streamer

on:
  workflow_dispatch:

jobs:
  streaming:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq curl

      - name: Fetch and Stream
        run: |
          # 1. جلب البيانات الطازجة
          DATA=$(curl -s "https://foxtv7.com/panel/url-stream/bein1.json")
          STREAM_URL=$(echo $DATA | jq -r '.url')
          USER_AGENT=$(echo $DATA | jq -r '.useragent')

          echo "Streaming from: $STREAM_URL"

          # 2. البث المباشر بدون الترويسة المسببة للمشكلة
          ffmpeg -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          -user_agent "$USER_AGENT" \
          -i "$STREAM_URL" \
          -c:v libx264 -preset superfast -c:a aac -f flv "rtmp://vsu.okcdn.ru/input/14611275587311_15327401544431_u6cwcdvuta"
