# استخدام ffmpeg مباشرة مع قناع متصفح حقيقي وسحب صيغة ts
ffmpeg -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
-i "http://po.vibertv.online:2086/live/11/11/623874.ts" \
-c:v copy -c:a copy -f flv \
"rtmp://vsu.okcdn.ru/input/14639543099119_15378990566127_kh5yrivxcm"
